name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v3
      - run: npm i
      - run: npm run build-storybook
      - run: touch storybook-static/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: storybook
          folder: storybook-static
          clean: true
